version: "3.8"
services:
  db:
    restart: always
    image: mysql:5.7
    container_name: playground-app-db
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_HOST: localhost
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "playground-app"